#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/d387a401-7dd7-44a2-9a14-79150c4dcf3c/ # 
title: Onlineshoping
version: 1

/products:
  get:
    responses:
      200:
        body:
          application/json:
            examples:
              {"categoryid": 0,
           "description": "string",
           "name": "string",
           "price": 0,
           "productid": 0,
           "video_url": "string"}
           

          
            

            
     
        
      